security:
    providers:
        restaurantes:
            entity:
                class: App\Entity\Restaurante
                property: correo

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            form_login:
                login_path: /login
                check_path: /check
                default_target_path: pagina_usuario
            provider: restaurantes
